In [1]:
import pandas as pd
df = pd.read_csv('ecommerce_raw.csv')
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [2]:
df.shape

(250000, 13)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  str
 2   Product Category       250000 non-null  str
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  str
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  str
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  str
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), str(5)
memory usage: 37.0 MB

In [4]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,202618.000000,250000.000000,250000.00000
mean,25017.632092,254.742724,3.004936,2725.385196,43.798276,0.500824,43.798276,0.20052
std,14412.515718,141.738104,1.414737,1442.576095,15.364915,0.500001,15.364915,0.40039
min,1.000000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000,0.00000
25%,12590.000000,132.000000,2.000000,1476.000000,30.000000,0.000000,30.000000,0.00000
50%,25011.000000,255.000000,3.000000,2725.000000,44.000000,1.000000,44.000000,0.00000
75%,37441.250000,377.000000,4.000000,3975.000000,57.000000,1.000000,57.000000,0.00000
max,50000.000000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.00000

In [5]:
df.describe(include=['object', 'string'])

,Purchase Date,Product Category,Payment Method,Customer Name,Gender
count,250000,250000,250000,250000,250000
unique,249728,4,3,39878,2
top,2021-12-25 13:07:57,Electronics,Credit Card,Michael Johnson,Male
freq,2,62630,83547,119,125676

In [6]:
# verification des valeurs manquantes
df.isnull().sum()
df = df.dropna(subset=['Returns'])

In [7]:
#verification des doublons
print(df.duplicated().sum())
df = df.drop_duplicates()
# la colonnes 'customer age' et 'age' sont les meme on peut supprimer l'une d'entre elles
df = df.drop(columns=['Customer Age'])

0

In [8]:
#verification des types de données
df.dtypes

Customer ID                int64
Purchase Date                str
Product Category             str
Product Price              int64
Quantity                   int64
Total Purchase Amount      int64
Payment Method               str
Returns                  float64
Customer Name                str
Age                        int64
Gender                       str
Churn                      int64
dtype: object

In [9]:
# changer les types de données
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])
df['Returns'] = df['Returns'].astype(int)

In [10]:
# ajouter des underscores aux noms de colonnes composés de plusieurs mots
df.columns = df.columns.str.replace(' ', '_')

In [11]:
# enregistrer le dataframe nettoyé dans un nouveau fichier CSV
df.to_csv('ecommerce_cleaned.csv', index=False)